package protocols.dhcp.option;

public enum DHCPOption {
    PAD(0, "Pad"),
    SUBNET_MASK(1, "Subnet Mask"),
    TIME_OFFSET(2, "Time Offset"),
    ROUTER(3, "Router"),
    TIME_SERVER(4, "Time Server"),
    NS(5, "Name Server"),
    DNS(6, "Domain Name Server"),
    LOG_SERVER(7, "Log Server"),
    QUOTE_SERVER(8, "Quote Server"),
    LPR_SERVER(9, "LPR Server"),
    IMPRESS_SERVER(10, "Impress Server"),
    RLS(11, "Resource Location Server"),
    HOSTNAME(12, "Host Name"),
    BFS(13, "Boot File Size"),
    MDF(14, "Merit Dump File"),
    DOMAIN_NAME(15, "Domain Name"),
    SS(16, "Swap Server"),
    ROOT_PATH(17, "Root Path"),
    EXTENSIONS_PATH(18, "Extensions Path"),
    IP_FORWARDING(19, "IP Forwarding enable/disable"),
    NLSR(20, "Non-local Source Routing enable/disable"),
    POLICY_FILTER(21, "Policy Filter"),
    MDRS(22, "Maximum Datagram Reassembly Size"),
    DEFAULT_TTL(23, "Default IP Time-to-live"),
    PMAT(24, "Path MTU Aging Timeout"),
    PMPT(25, "Path MTU Plateau Table"),
    IM(26, "Interface MTU"),
    ASL(27, "All Subnets are Local"),
    BROADCAST(28, "Broadcast Address"),
    PMD(29, "Perform Mask Discovery"),
    MASK_SUPPLIER(30, "Mask supplier")
}
